INSERT INTO GAMES(id, name, description, developer, publisher, price) VALUES (1, 'Cyberpunk 2077', 'Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.', 'CD Projekt Red', 'CD Projekt', 30);
INSERT INTO GAMES(id, name, description, developer, publisher, price) VALUES (2, 'The Witcher', 'It is based on the book series of the same name by Polish writer Andrzej Sapkowski. The Witcher follows the story of Geralt of Rivia, a solitary monster hunter, who struggles to find his place in a world.', 'CD Projekt Red', 'CD Projekt', 10);
INSERT INTO GAMES(id, name, description, developer, publisher, price) VALUES (3, 'The Witcher 2: Assassins of Kings', 'Geralt has been essentially drafted as King Foltests personal bodyguard and the king is engaged in a battle with troops loyal to his mistress, the Baroness Mary Louisa La Valette after what can best be described as a lovers spat.', 'CD Projekt Red', 'CD Projekt', 15);
INSERT INTO GAMES(id, name, description, developer, publisher, price) VALUES (4, 'The Witcher 3: Wild Hunt', 'The Witcher 3: Wild Hunt is an action role-playing games with a third-person perspective. Players control Geralt of Rivia, a monster slayer known as a Witcher.', 'CD Projekt Red', 'CD Projekt', 20);


INSERT INTO USERS(email, name, password) VALUES ('alma@korte.hu', 'Alma Korte', '12345678');
INSERT INTO USERS(email, name, password) VALUES ('dinnye@ananasz.hu', 'Dinnye Ananasz', '12345678');
INSERT INTO USERS(email, name, password) VALUES ('mango@narancs.hu', 'Mango Narancs', '12345678');
INSERT INTO USERS(email, name, password) VALUES ('szilva@eper.hu', 'Szilva Eper', '12345678');